# Site settings
author: Jeremy Schuurmans
title: Zen and the Art of Programming
header-img: img/home-bg.png
email: jeremyschuurmans@gmail.com
copyright_name: Jeremy Schuurmans
description: > # this means to ignore newlines until "baseurl:"
  Thoughts along the way.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: JMSchuurmans
github_username:  JMSchuurmans

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
